In [2]:
from sklearn import preprocessing
import numpy as np
X = np.array([[ 1., -1.,  2.],
               [ 2.,  0.,  0.],
               [ 0.,  1., -1.]])
X_scaled = preprocessing.scale(X)

X_scaled                                          


array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [3]:
X_scaled.mean(axis=0)

array([0., 0., 0.])

In [4]:
X_scaled.std(axis=0)

array([1., 1., 1.])

In [5]:
scaler = preprocessing.StandardScaler().fit(X)
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [6]:
scaler.mean_

array([1.        , 0.        , 0.33333333])

In [7]:
scaler.scale_

array([0.81649658, 0.81649658, 1.24721913])

In [8]:
scaler.transform(X)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [27]:
X1 = np.array([[1.0,0,0],
             [1,1,0],
             [1,0,1],
             [0,0,0],
             [1,1,1],
              [1,1,0]])
X1

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 0., 1.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 0.]])

In [28]:
X1_sc = scaler.transform(X1)
X1_sc

array([[ 0.        ,  0.        , -0.26726124],
       [ 0.        ,  1.22474487, -0.26726124],
       [ 0.        ,  0.        ,  0.53452248],
       [-1.22474487,  0.        , -0.26726124],
       [ 0.        ,  1.22474487,  0.53452248],
       [ 0.        ,  1.22474487, -0.26726124]])

In [29]:
X1_sc.mean(axis=0)

array([-2.04124145e-01,  6.12372436e-01,  3.70074342e-17])

In [30]:
X1_scaled = preprocessing.scale(X1)
X1_scaled

array([[ 0.4472136 , -1.        , -0.70710678],
       [ 0.4472136 ,  1.        , -0.70710678],
       [ 0.4472136 , -1.        ,  1.41421356],
       [-2.23606798, -1.        , -0.70710678],
       [ 0.4472136 ,  1.        ,  1.41421356],
       [ 0.4472136 ,  1.        , -0.70710678]])

In [31]:
X1_scaled.mean(axis=0)

array([-1.29526020e-16,  0.00000000e+00,  7.40148683e-17])

In [32]:
X1_scaled.std(axis=0)

array([1., 1., 1.])